dc801/ctf/urls.py
import os.path
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from ctf import views
site_media = os.path.join(os.path.dirname(__file__), 'site_media')

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    #(r'^user/(\w+)/$', user_page),
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', views.logout_page, name='logout'),
    url(r'^register/$', views.register_page, name='register'),
    url(r'^register/success/$', views.register_success,name='sucess'),
    url(r'^flag_submit/$', views.flag_submit,name='flag_submit'),
    url(r'^score_board/$',views.score_board,name='score_board'),
    #{ 'template': 'registration/register_success.html' }),
    #(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
    #{ 'document_root': site_media }),
   # url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
   # url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
   # url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

dc801/dc801/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'dc801.views.home', name='home'),
    # url(r'^dc801/', include('dc801.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('ctf.urls',namespace="ctf")),
    #url(r'ctf/^', include('ctf.urls',namespace="ctf")),
    #url(r'^admin/', include(admin.site.urls)),

)

dc801/ctf/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class CTF_Game(models.Model):
    name        = models.CharField(max_length=254)
    start_time  = models.DateTimeField('Date Game Starts')
    end_time    = models.DateTimeField('Date Game Ends')
    description = models.CharField(max_length=254)


class Flag(models.Model):

    flag    = models.CharField(max_length=254)
    notes   = models.CharField(max_length=254)
    game_id = models.IntegerField(default=0)

    def __unicode__(self):
        return self.flag
    
class Capture(models.Model):
    flag            = models.ForeignKey(Flag)
    capture_date    = models.DateTimeField('Date flags was captured')
    user            = models.ForeignKey(User)


# Create your models here.

dc801/ctf/forms.py
import re
from django import forms as forms
from django.contrib.auth.models import User


class RegistrationForm(forms.Form):
  username = forms.CharField(label='Username', max_length=30)
  email = forms.EmailField(label='Email')
  password1 = forms.CharField(
    label='Password',
    widget=forms.PasswordInput()
  )
  password2 = forms.CharField(
    label='Password (Again)',
    widget=forms.PasswordInput()
  )

  def clean_username(self):
    username = self.cleaned_data['username']
    if not re.search(r'^\w+$', username):
      raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
    try:
      User.objects.get(username=username)
    except:
      return username
    raise forms.ValidationError('Username is already taken.')

  def clean_password2(self):
    if 'password1' in self.cleaned_data:
      password1 = self.cleaned_data['password1']
      password2 = self.cleaned_data['password2']
      if password1 == password2:
        return password2
    raise forms.ValidationError('Passwords do not match.')



class FlagSubmitForm(forms.Form):
    flag = forms.CharField(widget=forms.TextInput(attrs={'size':'40'}))

dc801/ctf/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.template import Context, loader
from django.template import RequestContext
from django.shortcuts import render_to_response
from ctf.forms import *
from ctf.models import *
from datetime import datetime  
import time

def index(request):

    if not request.user.is_authenticated():
        return render_to_response('ctf/index.html', RequestContext(request))
    user_captures = Capture.objects.filter(user=request.user)
    score = len(user_captures)
    return render_to_response('ctf/index.html', RequestContext(request,{'my_captures':user_captures,'score':score}))

def login(request):

    if request.method == 'POST':
        user_name = request.POST['username']
        u_password = request.POST['password']

        user = authenticate(username=user_name, password=u_password)

        if user is not None:
            if user.is_active:
                print "You provided a correct username and password!"
            else:
                print "Your account has been disabled!"
        else:
            print "Your username and password were incorrect."
    else:
        return render_to_response('ctf/login.html',variables)

def score_board(request):
    users_list = Capture.objects.raw('select id,username from auth_user')
    user_scores = []
    for a_user in users_list:
        score = Capture.objects.filter(user__id__exact=a_user.id)
        user_scores.append( {'username': a_user.username , 'score': len(score)})
    #sorted(user_scores,key=lambda scores: scores[1])   
    list = sorted(user_scores,key=lambda k: k['score'])
    return render_to_response('ctf/score_board.html',RequestContext(request,{'user_scores':reversed(list)}))

def flag_submit(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login')
    if request.method == 'POST':
        form = FlagSubmitForm(request.POST)

        if form.is_valid():
            temp_flag = form.cleaned_data['flag'].strip()
            flag_result = Flag.objects.filter(flag__exact=temp_flag)
            if len(flag_result) > 0 :

                flag_obj = flag_result[0]
                capture_result = Capture.objects.filter(flag=flag_obj).filter(user=request.user)

                if len(capture_result) > 0:
                    message= 'You have already captured flag %s.'
                    variables = RequestContext(request, {'form': form,'capture_msg': message})
                    return render_to_response('ctf/flag_submit.html',variables)
                    #return HttpResponse('flag found %s , yours ' % cap.id)
                else:   
                    
                    cap = Capture(flag=flag_obj,user=request.user,capture_date=datetime.now())
                    cap.save()
                    message = "Flag captured"
                    variables = RequestContext(request, {'form': form,'capture_msg': message})
                    return render_to_response('ctf/flag_submit.html',variables)
                    #return HttpResponse('flag found %s , yours ' % cap.id)
            else:
                message = 'Flag not found'
                variables = RequestContext(request, {'form': form,'capture_msg':message})
                return render_to_response('ctf/flag_submit.html',variables)
                #return HttpResponse('No Flags found')
    else:
        form = FlagSubmitForm()
        variables = RequestContext(request, {'form': form})
        #return render_to_response('registration/register.html', variables)
        return render_to_response('ctf/flag_submit.html',variables)

def register_success(request):
  return render_to_response('registration/register_success.html', RequestContext(request))

def logout_page(request):
  logout(request)
  return HttpResponseRedirect('/')


def register_page(request):
  if request.method == 'POST':
    form = RegistrationForm(request.POST)
    if form.is_valid():
      user = User.objects.create_user(
        username=form.cleaned_data['username'],
        password=form.cleaned_data['password1'],
        email=form.cleaned_data['email']
      )
      return HttpResponseRedirect('/register/success/')
  else:
    form = RegistrationForm()

  variables = RequestContext(request, {
    'form': form
  })
  return render_to_response('registration/register.html', variables)

dc801/ctf/templates/ctf/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title>DC801 CTF | {% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="/site_media/style.css" type="text/css" />
</head>

<body>
  <div id="nav">
    <a href="/">home</a> |
    <a href="/score_board/">score_board</a>
    {% if user.is_authenticated %}   
    <a href="/flag_submit/">flag_submit</a>
       {{ user.username }}
      (<a href="/logout/">logout</a>)
    {% else %}
      <a href="/login/">login</a> |
      <a href="/register/">register</a> |
      <a href="kali-linux-1.0.1-amd64.iso">Kali Linux</a>
    {% endif %}
  </div>
  <h1>{% block head %}{% endblock %}</h1>
  {% block content %}{% endblock %}
</body>
</html>

dc801/ctf/templates/ctf/flag_submit.html
{% extends "ctf/base.html" %}

{% block title %}DC801 Open West FFA CTF 2013{% endblock %}
{% block head %}DC801 Open West FFA CTF 2013{% endblock %}

{% block content %}

{{capture_msg}}
<form action="/flag_submit/" method="post">{% csrf_token %}
{{ form.non_field_errors }}
<div class="fieldWrapper">
        {{ form.flag.errors }}
        <label for="id_flag"a>Enter Flag:</label>
        {{ form.flag}}
</div>
<input type="submit" value="Submit" />
</form>
{% endblock %}

dc801/ctf/templates/ctf/index.html
{% extends "ctf/base.html" %}

{% block title %}DC801 Open West FFA CTF 2013{% endblock %}
{% block head %}DC801 Open West FFA CTF 2013{% endblock %}

{% block content %}
  {% if user.username %}
    <p> {{ user.username }}! Score {{score}} </p>
        <p>click here to <a href="/flag_submit">Submit Flags</a></p>
        {% if my_captures %}
            <ul>
            {% for capture in my_captures %}   
                  <p>
                    Captured Flag:
                    {{capture.flag.id}}
                    Captured Date:
                    {{capture.capture_date}}
                  </p>
            {% endfor %}
        </ul>
        {% else %}
                <p>No captures as of yet!</p>
        {% endif %}
  {% else %}
    <p>Welcome anonymous user! 
      You need to <a href="/login">login</a>
      or <a href="/register">register</a>
      before you can submit flags</p>
    <p>Rules: DO NOT ATTACK THE SCORING SERVER! NO physical ATTACKS! </p>
    <p>Example Flag: 0f3dd248cda04eee8de760c932e1810360d2ad9a</p>
  {% endif %}
{% endblock %}

dc801/ctf/templates/ctf/login.html
{% extends "ctf/base.html" %}

{% block title %}User Login{% endblock %}
{% block head %}User Login{% endblock %}

{% block content %}
  {% if form.has_errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
    <p><label for="id_username">Username:</label>{{ form.username }}</p>
    <p><label for="id_password">Password:</label>{{ form.password }}</p>
    <input type="hidden" name="next" value="/" />
    <input type="submit" value="login" />
  </form>
{% endblock %}

dc801/ctf/templates/ctf/score_board.html
{% extends "ctf/base.html" %}

{% block title %}DC801 Open West FFA CTF 2013{% endblock %}
{% block head %}DC801 Open West FFA CTF 2013{% endblock %}


{% block content %}

<p> ONLY ATTACK these networks WIRED 10.108.69.0/24 and WIRESS SSID HACKME2 10.108.30.0/24</p>

{% if user_scores %}
    <div>
    <table>
    <tr>
    <th>User</th>
    <th>Score</th>
    </tr>
    {% for score in user_scores%} 
        <tr>
          <td>{{score.username}} </td> <td>{{score.score}}</td>
        </tr>
    {% endfor %}
    </table>
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

dc801/ctf/templates/ctf/user_page.html
{% extends "ctf/base.html" %}

{% block title %}{{ username }}{% endblock %}
{% block head %}Bookmarks for {{ username }}{% endblock %}

{% block content %}
  {% if bookmarks %}
    <ul>
      {% for bookmark in bookmarks %}
        <li><a href="{{ bookmark.link.url }}">
          {{ bookmark.title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No bookmarks found.</p>
  {% endif %}
{% endblock %}